CI: run profcheck tests (#146)
Tests in `profcheck` do fail with recent changes:

```
--- FAIL: TestCheckConformance (0.00s)
    --- FAIL: TestCheckConformance/sample_with_multiple_values (0.00s)
        check_test.go:368: Check(): got no error, want error containing "must contain a single element if timestamps_unix_nano is not set"
FAIL
FAIL	github.com/open-telemetry/sig-profiling/profcheck	0.005s
?   	github.com/open-telemetry/sig-profiling/profcheck/cmd/profcheck	[no test files]
```

I didn't notice this issue due to caching issues. To prevent such issues
in the future, add a CI job that runs profcheck tests.

Signed-off-by: Florian Lehner <dev@der-flo.net>